
import type { Patient } from '@/types/patient';

type MockPatientData = Omit<Patient, 'id' | 'bedNumber' | 'roomDesignation' | 'gridRow' | 'gridColumn' | 'admitDate' | 'dischargeDate'>;

export const mockPatientData: MockPatientData[] = [
  {
    name: "Eleanor Vance",
    age: 72,
    gender: "Female",
    chiefComplaint: "Acute exacerbation of COPD, shortness of breath.",
    ldas: ["2L NC", "PIV R AC"],
    diet: "Cardiac Diet",
    mobility: "Assisted",
    codeStatus: "DNR/DNI",
    orientationStatus: "x3",
    assignedNurse: "RN Alice",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Family meeting scheduled for 14:00. Awaiting chest X-ray results.",
  },
  {
    name: "Marcus Holloway",
    age: 45,
    gender: "Male",
    chiefComplaint: "Post-op day 1 from appendectomy, pain management.",
    ldas: ["PIV L Hand", "Jackson-Pratt Drain"],
    diet: "Clear Liquids",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Bob",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Encourage incentive spirometer use every hour. Medicate for pain before ambulation.",
  },
  {
    name: "Sofia Rossi",
    age: 81,
    gender: "Female",
    chiefComplaint: "Altered mental status, suspected UTI.",
    ldas: ["Foley Catheter", "PIV R Forearm"],
    diet: "Regular",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    assignedNurse: "RN Charlie",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Urine culture sent. Needs 1:1 sitter for safety due to confusion.",
  },
  {
    name: "David Chen",
    age: 58,
    gender: "Male",
    chiefComplaint: "Chest pain, rule out myocardial infarction.",
    ldas: ["2 PIVs (L/R AC)", "Telemetry"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN David",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Troponin levels q6h. Nitroglycerin sublingual PRN for chest pain.",
  },
  {
    name: "Jasmine Kaur",
    age: 34,
    gender: "Female",
    chiefComplaint: "Community-acquired pneumonia.",
    ldas: ["PIV L Wrist"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Mallory",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: true,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "On IV Levaquin. Monitor for respiratory distress.",
  },
  {
    name: "Robert Miller",
    age: 67,
    gender: "Male",
    chiefComplaint: "Cellulitis of left lower leg.",
    ldas: ["PIV R Hand"],
    diet: "Diabetic Diet (ADA)",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Judy",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Elevate left leg. Outline area of redness to monitor for changes.",
  },
];
