
import type { Patient } from '@/types/patient';

type MockPatientData = Omit<Patient, 'id' | 'bedNumber' | 'roomDesignation' | 'gridRow' | 'gridColumn' | 'admitDate' | 'dischargeDate'>;

export const mockPatientData: MockPatientData[] = [
  {
    name: "Eleanor Vance",
    age: 72,
    gender: "Female",
    chiefComplaint: "COPD exacerbation",
    ldas: ["2L NC", "PIV R AC"],
    diet: "Cardiac Diet",
    mobility: "Assisted",
    codeStatus: "DNR/DNI",
    orientationStatus: "x3",
    assignedNurse: "RN Alice",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Family meeting at 14:00. Awaiting chest X-ray results.",
  },
  {
    name: "Marcus Holloway",
    age: 45,
    gender: "Male",
    chiefComplaint: "Post-op appendectomy",
    ldas: ["PIV L Hand", "JP Drain"],
    diet: "Clear Liquids",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Bob",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Incentive spirometer q1h. Medicate for pain before ambulation.",
  },
  {
    name: "Sofia Rossi",
    age: 81,
    gender: "Female",
    chiefComplaint: "Altered mental status",
    ldas: ["Foley Catheter"],
    diet: "Regular",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    assignedNurse: "RN Charlie",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Suspected UTI. Urine culture sent. Needs 1:1 sitter.",
  },
  {
    name: "David Chen",
    age: 58,
    gender: "Male",
    chiefComplaint: "Chest pain, r/o MI",
    ldas: ["2 PIVs (AC)", "Telemetry"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN David",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Troponins q6h. NTG PRN.",
  },
  {
    name: "Jasmine Kaur",
    age: 34,
    gender: "Female",
    chiefComplaint: "Pneumonia",
    ldas: ["PIV L Wrist"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Mallory",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: true,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "On IV Levaquin. Monitor for respiratory distress.",
  },
  {
    name: "Robert Miller",
    age: 67,
    gender: "Male",
    chiefComplaint: "Cellulitis LLE",
    ldas: ["PIV R Hand"],
    diet: "Diabetic Diet (ADA)",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Judy",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Elevate LLE. Outline redness.",
  },
  {
    name: "Isabella Garcia",
    age: 29,
    gender: "Female",
    chiefComplaint: "Migraine with aura",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Quiet, dark room. IV fluids for hydration.",
  },
  {
    name: "Liam O'Connell",
    age: 78,
    gender: "Male",
    chiefComplaint: "Fall at home, hip fx",
    ldas: ["PIV L FA"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Ortho consult pending. Scheduled for surgery in AM.",
  },
  {
    name: "Ava Nguyen",
    age: 52,
    gender: "Female",
    chiefComplaint: "New onset seizures",
    ldas: ["PIV R AC"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Keppra load given. EEG scheduled.",
  },
  {
    name: "Jackson Williams",
    age: 63,
    gender: "Male",
    chiefComplaint: "GI Bleed",
    ldas: ["2 large bore PIVs"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "DNR/DNI",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Serial H&H. GI consult placed.",
  },
  {
    name: "Olivia Brown",
    age: 40,
    gender: "Female",
    chiefComplaint: "DKA",
    ldas: ["Insulin Drip", "PIV"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Hourly glucose checks. Monitor potassium levels.",
  },
  {
    name: "Noah Patel",
    age: 88,
    gender: "Male",
    chiefComplaint: "Dehydration",
    ldas: ["PIV L Hand"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Encourage PO fluids. IV fluids running at 75ml/hr.",
  },
  {
    name: "Emma Wilson",
    age: 19,
    gender: "Female",
    chiefComplaint: "Suicidal Ideation",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "1:1 sitter for safety. Psych consult placed.",
  },
  {
    name: "Lucas Martinez",
    age: 65,
    gender: "Male",
    chiefComplaint: "A-fib with RVR",
    ldas: ["PIV", "Telemetry"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Cardizem drip. Monitor heart rate and BP closely.",
  },
  {
    name: "Mia Johnson",
    age: 75,
    gender: "Female",
    chiefComplaint: "CVA",
    ldas: ["NG Tube", "PIV"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Speech therapy consult for swallow evaluation.",
  },
  {
    name: "Ethan Taylor",
    age: 31,
    gender: "Male",
    chiefComplaint: "Kidney stone",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Strain all urine. Pain management with Toradol.",
  },
  {
    name: "Avery Scott",
    age: 25,
    gender: "Female",
    chiefComplaint: "Asthma exacerbation",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Continuous nebulizer treatments. Monitor O2 sats.",
  },
  {
    name: "Benjamin Green",
    age: 92,
    gender: "Male",
    chiefComplaint: "Failure to thrive",
    ldas: [],
    diet: "Pureed",
    mobility: "Assisted",
    codeStatus: "DNR",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isComfortCareDNR: true,
    notes: "Hospice consult. Focus on comfort measures.",
  },
  {
    name: "Chloe King",
    age: 48,
    gender: "Female",
    chiefComplaint: "Pancreatitis",
    ldas: ["PIV"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Aggressive IV fluids. Pain management with Dilaudid PCA.",
  },
  {
    name: "Daniel Wright",
    age: 55,
    gender: "Male",
    chiefComplaint: "Alcohol withdrawal",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "CIWA protocol. Ativan PRN.",
  },
  {
    name: "Harper Lee",
    age: 22,
    gender: "Female",
    chiefComplaint: "Anorexia nervosa",
    ldas: ["Central Line"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Monitor for refeeding syndrome. Strict I&Os.",
  },
  {
    name: "Logan Hill",
    age: 38,
    gender: "Male",
    chiefComplaint: "Deep vein thrombosis",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Heparin drip. Monitor PTT. No IM injections.",
  },
  {
    name: "Evelyn Reed",
    age: 85,
    gender: "Female",
    chiefComplaint: "Sepsis",
    ldas: ["Central Line", "Foley"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Broad-spectrum antibiotics. Monitor lactate levels.",
  },
  {
    name: "Mason Cook",
    age: 50,
    gender: "Male",
    chiefComplaint: "Liver failure",
    ldas: ["PICC Line"],
    diet: "Renal Diet",
    mobility: "Assisted",
    codeStatus: "DNR/DNI",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Monitor for asterixis. Lactulose for ammonia levels.",
  },
  {
    name: "Scarlett Bell",
    age: 68,
    gender: "Female",
    chiefComplaint: "Hypertensive crisis",
    ldas: ["Arterial Line", "PIV"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Nicardipine drip. Frequent neuro checks.",
  },
  {
    name: "Grayson Morgan",
    age: 71,
    gender: "Male",
    chiefComplaint: "Urinary retention",
    ldas: ["Foley Catheter"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Urology consult. Flomax started.",
  },
  {
    name: "Zoe Cooper",
    age: 28,
    gender: "Female",
    chiefComplaint: "Sickle cell crisis",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Pain management and hydration are priorities.",
  },
  {
    name: "Caleb Rivera",
    age: 60,
    gender: "Male",
    chiefComplaint: "Gout flare",
    ldas: [],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Colchicine and NSAIDs. Bed cradle to keep sheets off feet.",
  },
  {
    name: "Lillian Powell",
    age: 95,
    gender: "Female",
    chiefComplaint: "Social admit",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "DNR",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Awaiting nursing home placement. Case management involved.",
  },
  {
    name: "Henry Long",
    age: 82,
    gender: "Male",
    chiefComplaint: "Congestive heart failure",
    ldas: ["PIV"],
    diet: "Cardiac Diet",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Strict I&Os. Daily weights. Lasix IV.",
  },
  {
    name: "Aurora Hughes",
    age: 44,
    gender: "Female",
    chiefComplaint: "Post-op Mastectomy",
    ldas: ["JP Drain", "PIV"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "No BPs or IVs in left arm. Monitor drain output.",
  },
  {
    name: "Wyatt Peterson",
    age: 77,
    gender: "Male",
    chiefComplaint: "Shingles",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: true,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Airborne and contact precautions. Acyclovir administered.",
  }
];
